version: "3.7"
services:
    server:
        build:
            context: .
            dockerfile: Dockerfile-server
        environment:
            - PL_PWA_URL
            - PL_EMAIL_USER
            - PL_EMAIL_SERVER
            - PL_EMAIL_PORT
            - PL_EMAIL_PASSWORD
            - PL_EMAIL_FROM
            - PL_REPORT_ERRORS
            - PL_BILLING_ENABLED
            - PL_BILLING_STRIPE_SECRET
            - PL_BILLING_STRIPE_PUBLIC_KEY
            - PL_MFA
            - PL_REPL_PORT
        ports:
            - "${PL_SERVER_PORT:-3000}:3000"
            - "${PL_BILLING_PORT:-4000}:4000"
        volumes:
            - db-vol-1:/data
            - docs-vol-1:/docs
            - logs-vol-1:/logs
        networks:
          internal:
            aliases:
              - server
    pwa:
        build:
            context: .
            dockerfile: Dockerfile-pwa
        environment:
            - PL_SUPPORT_EMAIL
            - PL_SERVER_URL
            - PL_PWA_URL
            - PL_BILLING_ENABLED
            - PL_BILLING_STRIPE_PUBLIC_KEY
        ports:
            - "${PL_PWA_PORT:-8080}:8080"
        volumes:
            - pwa-vol-1:/pwa
        networks:
          internal:
            aliases:
              - pwa
        command: ["build_and_start"]

networks:
  internal:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-padloc

volumes:
  logs-vol-1:
  db-vol-1:
  pwa-vol-1:
  docs-vol-1:

